version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
        
  local.flexy:
    container_name: local.flexy.com.br
    image: flexy
    volumes:
      - ".:/var/www/html/:rw"
    environment:
      VIRTUAL_HOST: local.flexy.com.br
      pwd: '/var/www/html/'
      ENV_ALIAS: 'dev'
      #DATABASE
      DB_HOST: 'local.db'
      DB_PORT: '3306'
      DB_DATABASE: 'flexy'
      DB_USERNAME: 'root'
      DB_PASSWORD: 'root'
    build: .docker/
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - local.db
    command: ./assemble
    tty: true
    #command: sleep 80000

  local.db:
    container_name: local.db
    image: mariadb
    volumes:
      - "./db/local:/var/lib/mysql"
      - "./migrations:/var/migrations"
      - "./migrations:/docker-entrypoint-initdb.d/:ro"
    environment:
      VIRTUAL_HOST: local.db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flexy
    ports:
      - "3306:3306"
    expose:
      - "3306"
    #build: ./migrations/

  local.pma:
    image: phpmyadmin/phpmyadmin
    container_name: local.pma.com.br
    environment:
      VIRTUAL_HOST: local.pma
      PMA_HOST: local.db
    volumes:
      - /sessions